# Generated by Django 2.2.11 on 2020-04-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Please type a new catogory', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'StockCategories',
                'verbose_name': 'StockCategory',
                'db_table': 'stock_category',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Please type the name of the produce', max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fridge.StockCategory')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Stocks',
                'verbose_name': 'Stock',
                'db_table': 'stock',
            },
        ),
    ]
