# Generated by Django 2.2.11 on 2020-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_auto_20200405_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='abreviature',
            field=models.CharField(default='Unit', max_length=4),
        ),
    ]
