# Generated by Django 2.2.11 on 2020-04-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_fridgeenvirontment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Type the name and surname of the supplier', max_length=200)),
                ('is_company', models.BooleanField(default=False)),
                ('phone', models.CharField(default='+39-1234-5678', max_length=13)),
                ('address', models.TextField(default='Type the address of the supplier')),
            ],
            options={
                'db_table': 'suppliers',
                'managed': True,
                'verbose_name_plural': 'Suppliers',
                'verbose_name': 'Supplier',
            },
        ),
    ]
