# Generated by Django 2.2.11 on 2020-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='supplier@company.com', max_length=254),
        ),
    ]
